<a href="https://colab.research.google.com/github/maenohiroki1123/DeepLearning2022Late/blob/main/10_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([1.0,2.0,3.0,4.0,5.0])
print(x)

x=np.array([1,2,3])
print(x)
print(type(x))

my_list1=[1,2,3,4,5]
my_array1=np.array(my_list1)

my_list2=[10,20,30,40,50]
my_lists=[my_list1,my_list2]
my_lists

my_array2=np.array(my_lists)

my_array2

[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [3]:
a=np.array([1,2,3,4])
a.shape

b=np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [4]:
x=np.arange(10)
print(x)

x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)

print(x)
print(y)

print(x+y)
print(x-y)
print(x*y)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [5]:
sample_array=np.arange(10)
print(sample_array)

sample_array2=sample_array.reshape(2,5)
print(sample_array2)

sample_array3=np.array([[1,2,3],[4,5,6]])
sample_array4=np.array([[7,8,9],[10,11,12]])

print(np.concatenate([sample_array3,sample_array4],axis=1))

print(np.hstack((sample_array3,sample_array4)))

print(np.concatenate([sample_array3,sample_array4],axis=0))

print(np.vstack((sample_array3,sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
sample_array=np.arange(10)
print(sample_array)

print(sample_array+5)


[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
n1=np.array([1,2,3,4,5])
print(n1)

np.ndim(n1)
n1.shape

n2=np.array([[1,2],[3,4],[5,6]])
print(n2)

print(n2.ndim)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
2


In [9]:
my_li1=[-1,4]
my_li2=[3,2]
my_li3=[2,5]
my_li4=[0,1]

my_lists=[my_li1, my_li2, my_li3, my_li4]

my_array3=np.array(my_lists)
my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])